version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Build started on `date`
      - npm install --production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
